language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t vbrake/docker-react -f Dockerfile.dev .i

script:
  - docker run -e CI=true vbrake/docker-react npm run test
